### ISSUE TITLE
Double Page zoom jumps upside down

### ISSUE THREAD

**Issue by katmin007** [Moult/iiviewer#2]
Former item 5 (double page jumps to upside down single page when zoomed in very far) still happens (please see screenshot attached)
![item 2](https://cloud.githubusercontent.com/assets/17059380/12806584/6fbe5442-cb5b-11e5-91af-f88f350a8942.JPG)

**Comment by Moult** [comment]
Cannot replicate. Please provide PDF.

**Comment by Moult** [comment]
A bit more investigation and I can replicate this bug. Turns out this is a known bug in Mozilla's PDF.js. There are multiple potential causes. Fixed.
