### ISSUE TITLE
Drag Page when zoomed

### ISSUE THREAD

**Issue by katmin007** [Moult/iiviewer#3]
Former item 6 (drag and scroll the page once zoomed in) does not work. That means you can’t really view the page in a zoomed in state. Please enable horizontal and vertical scrolling as well as dragging the page with the mouse so you can view it when zoomed in.

**Comment by Moult** [comment]
Cannot replicate. Please ensure you have set up the dependencies properly. (Ask Matt to reinstall all dependencies, I suspect he did not do so)

**Comment by katmin007** [comment]
As mentioned, Matt is on leave now. Please let's have a look once you are back - in the meantime we won't be able to further test.
