### ISSUE TITLE
Downloading favourited pages

### ISSUE THREAD

**Issue by katmin007** [Moult/iiviewer#5]
Downloading the favourited pages does not work (former item 10). Please see attached screenshot. Please fix.

**Comment by Moult** [comment]
No screenshot provided. Please also confirm you have set up the server dependencies properly as I mentioned.

**Comment by katmin007** [comment]
![item 5](https://cloud.githubusercontent.com/assets/17059380/12831576/3a9a0ab6-cbe9-11e5-8500-d54705f4965e.JPG)

**Comment by katmin007** [comment]
Matt is on leave now but he read your comments so I presume it should be fine. If you can't find the reason for this issue, we can revisit once you are back. You can then have a look at the set-up

**Comment by Moult** [comment]
It looks like Matt indeed has not properly set up pdftk as a dependency. To double confirm this, you can also check if any other PDFs are appearing in the pdf directory. If none are appearing, he probably did not set it up properly.

However, the screenshot also looks weird in that the filename is not what I expect. Perhaps Matt changed the code in some way, or the set up on your computer is non-standard.

**Comment by katmin007** [comment]
Since Matt is not here at the moment and it is set up on his localhost, let's please re-visit once you are in the office :)

**Comment by katmin007** [comment]
Please open download in a new tab
