### ISSUE TITLE
Toggling a leading page in double page view

### ISSUE THREAD

**Issue by katmin007** [Moult/iiviewer#8]
Former item 9: you wrote “Also added support for toggling a leading page in double page view” – Can you please clarify what you mean by that?

**Comment by Moult** [comment]
A leading page is whether the first page of the PDF is part of a spread or not.

A document with a leading page starts with page 1, then page 2-3 on a spread, 4-5 on a spread, etc. A document with no leading page starts with page 1-2 on a spread, 3-4 on a spread, etc.

The ability to set this is in the code.
